### ISSUE TITLE
Update profanity filter for kids mode

### ISSUE THREAD

**Issue by TLouison** [TLouison/StoryHop#5]
Certain words are still slipping past the profanity filter. Can someone merge [these](http://www.bannedwordlist.com/) with the ones in ours currently? Here are another few the filter likely wont catch (link to words to avoid profanity on the official repo, contains VERY OFFENSIVE CONTENT): https://pastebin.com/MQwYfC4w

**Comment by TLouison** [comment]
Also if anyone else has words they would like to contribute feel free to add them

**Comment by hertacalvo** [comment]
All set
